### PR TITLE
Enable SSR Rendering of alert components

### PR DESCRIPTION
**Pull request by TheAncientGoat**

### CODE REVIEW

**Comment by djorg83** [comment]
I'll look into reviewing/merging this tomorrow.

**Comment by djorg83** [comment]
Why is there so much diff?

**Comment by TheAncientGoat** [comment]
Because the dist files are under the source tree (so the build output is different)? The only changes I made where like 5 lines on lib/components/SweetAlert.js and the version bump in package.json

**Comment by djorg83** [comment]
ok, you must have a slightly different versions of the babel plugins

**Comment by djorg83** [comment]
i think your code could have been simpler.

`if (window && window.innerWidth && window.innerWidth < 767) {
    style = objectAssign({}, style, styles.sweetAlertMobile);
}`

**Comment by djorg83** [comment]
im making a few enhancements now.  will publish this with the other changes.

**Comment by TheAncientGoat** [comment]
Accessing window directly without wrapping it in typeof results in an undefined variable error when doing SSR (not sure if it's being set as strict somewhere..); if you look at my first attempt https://github.com/djorg83/react-bootstrap-sweetalert/pull/4/commits/47dc8405bb4a335af62d9a1b31295a4df117adad - I implemented it similarly but it kept on crashing until everything was wrapped.

**Comment by djorg83** [comment]
fixed in published version 2.1.0

**Pull request closed without merging**
