### PR TITLE
Added custom show and hide animation

### LINKED ISSUE #18: Support close animation (feature request)
Nice job on this component, it would be cool to have support for the close animation too.
The API would need a `show` prop as an alternative to component mounting/unmounting to support animated hide like react-bootstrap does for modals. It's nothing high priority for me but a nice thing to have if possible.

Thanks for your work, have a nice day.

Edit: I just seen the show prop already exists, only the animation is missing then.

### PR DESCRIPTION
**Pull request by wouter140**
Added support for custom show and hide animations with the `openAnim` and `closeAnim` properties. 
I also added an example in the demo page with a hide animation and I updated the readme documentation with these new properties.

This implements the feature request in issue #18.

To add a custom animation just pass an object with the name and duration properties in the open or close Anim property. In the name property, you specify the CSS animation-name and the duration is the animation duration in ms. 
If setting `openAnim` and/or `closeAnim` property to false, there will not be an animation.

Closes #18

### CODE REVIEW

**Comment by djorg83** [comment]
@wouter140 would you mind resolving these conflicts?  I merged your newer PRs first and this one has some implementation in functions that no longer exist.

**Comment by wouter140** [comment]
The changes are not entirely correct. Am fixing the other stuff now in my branch. Will make a commit later tonight fixing all the last bits

**Comment by djorg83** [comment]
Sure. No problem.  I'm not publishing this until I have a chance to test everything and update the release notes.

**Comment by wouter140** [comment]
Was not able to add the new changes in this pr as its closed, so I made a new pr #53 with the fixes

**Comment by djorg83** [comment]
@wouter140 all of your added enhancements are now published in version 5.1.0.  I had to spend some time debugging the open/close animations to make them work without needing to provide props.show.  Now it works whenever you exit the alert without props.show needed.  I also renamed props.customActions to props.customButtons.  Thanks again for all of your contributions, you saved me a ton of time and effort.

**Pull request merged**
